config/routes.rb
Rails.application.routes.draw do
  root :to => 'searches#new'

  get "up" => "rails/health#show", as: :rails_health_check

  resources :searches, :only => %i[new create show] do
    collection do
      delete :destroy # until we have a Search model we can reference by ID.
      post :load_cached
    end
  end
end

app/models/search.rb
class Search

  include ActiveModel::Model

  attr_reader :flights
  attr_accessor :dep
  attr_accessor :arr
  attr_accessor :dep_on
  attr_accessor :currency

  def initialize(atts = {})
    atts.each do |k, v|
      send "#{k}=", v
    end
  end

  def call
    make_request
    parse_flights
    persist
    @flights = find_all
  end

  def to_model
    self
  end

  %i[dep arr].each do |dep_arr|
    define_method "#{dep_arr}=" do |v|
      instance_variable_set :"@#{dep_arr}", v.upcase
    end
  end

  def currency=(c)
    @currency = Currency.new(c)
  end

  def route
    @route ||= Route.new(@dep, @arr)
  end

 private

  def make_request
    request = Request.new(@dep, @arr, @dep_on, @currency)
    request.call
    @response = request.response
  end

  def parse_flights
    json = JSON.load(@response.body)
    #puts JSON.pretty_generate(json)
    @parsed_flights = Search::Parser.parse_all(json)
  end

  def persist
    @persister = Search::Persister.new(@parsed_flights, self)
    @persister.call
  end

  def find_all
    Flight.find(@persister.flight_ids)
  end

end

app/models/search/parser.rb
class Search::Parser

  class << self

    def parse_all(json)
      json
        .fetch('data')
        .fetch('searchResults')
        .fetch('airProducts')
        .first
        .fetch('details')
        .map(&Search::Parser::Flight.method(:new))
    end

    def parse_response(response)
      parse_json_string(response.body)
    end

    def parse_json_string(str)
      json = JSON.parse(str)
      parse_all json
    end

    def parse_file(path)
      parse_json_string(File.read(path))
    end

  end

end

app/models/search/parser/fare.rb
class Search::Parser::Fare

  class << self

    FARE_TYPE_IDENTS = %w[
      WGA
      WGARED
      PLURED
    ]

    def parse_from_flight(json)
      return nil unless json.key?('fareProducts')
      fare_json =
        json
          .fetch('fareProducts')
          .fetch('ADULT')
          .then do |n|
            keys = n.keys
            key = (FARE_TYPE_IDENTS & keys).first
            raise "No fare found from #{keys.inspect}" unless key
            n.fetch(key)
          end
      new(fare_json)
    end

  end

  def initialize(json)
    @json = json
  end

  def price
    return nil unless available?
    @json
      .fetch('fare')
      .fetch('totalFare')
      .then(&Search::Parser::Price.method(:new))
  rescue
    puts @json
    raise
  end

  def available?
    @json.fetch('availabilityStatus') == 'AVAILABLE'
  end

  def unavailable?
    !available?
  end

end

app/models/search/parser/flight.rb
class Search::Parser::Flight

  attr_accessor :flight_id

  def initialize(json)
    @json = json
  end

  def dep
    @dep ||= @json.fetch('originationAirportCode')
  end

  def arr
    @arr ||= @json.fetch('destinationAirportCode')
  end

  def dep_at
    @dep_ap ||= DateTime.parse(@json.fetch('departureDateTime'))
  end

  def arr_at
    @arr_ap ||= DateTime.parse(@json.fetch('arrivalDateTime'))
  end

  def price
    @price ||= fare.price
  end

  def unavailable?
    fare.unavailable?
  end

  def num_stops
    segments.size - 1 + segments.sum(&:num_stops)
  end

  def layover_airports
    @layover_airports ||=
      if num_stops > 0
        segments[0..-2].map(&:destination_airport_code)
      else
        []
      end
  end

  def duration
    @duration ||= Integer(@json.fetch('totalDuration'))
  end

  def fare
    @fare ||= Search::Parser::Fare.parse_from_flight(@json)
  end

  def ident
    [
      dep_at,
      arr_at,
    ].map(&:to_s).join('|')
  end

  def validate!
    dep_at
    arr_at
    duration
    num_stops
    layover_airports
    price
  rescue
    puts ident
    raise
  end

  def route
    "#{dep}-#{arr}"
  end

private

  def segments
    @segments ||= @json.fetch('segments').map(&Search::Parser::Segment.method(:new))
  end

end

app/models/search/parser/price.rb
class Search::Parser::Price

  TYPES = {
    'POINTS' => :points,
    'USD'    => :cash,
  }

  def initialize(json)
    @json = json
  end

  def value
    @json.fetch('value')
  end

  def currency
    @json.fetch('currencyCode')
  end

  def type
    TYPES.fetch(currency)
  end

  def to_s
    "#{value} #{currency}"
  end

  TYPES.values.each do |t|
    define_method "#{t}?" do
      type == t
    end
  end

end

app/models/search/parser/segment.rb
class Search::Parser::Segment

  def initialize(json)
    @json = json
  end

  def destination_airport_code
    @json.fetch('destinationAirportCode')
  end

  def num_stops
    @json.fetch('numberOfStops')
  end

end

app/models/search/persister.rb
class Search::Persister

  attr_reader :flight_ids

  def initialize(parsed_flights, search)
    @parsed_flights = parsed_flights
    @search         = search
    @flight_ids     = []
  end

  def call
    Flight.transaction do
      upsert_flights
      expire_flights
      upsert_fares
    end
  end

private

  def upsert_flights
    @flight_ids = @parsed_flights.map do |parsed_flight|
      flight_atts = {
        :dep              => parsed_flight.dep,
        :arr              => parsed_flight.arr,
        :dep_at           => parsed_flight.dep_at,
        :arr_at           => parsed_flight.arr_at,
        :duration         => parsed_flight.duration,
        :stops            => parsed_flight.num_stops,
        :layover_airports => parsed_flight.layover_airports.join(',').presence
      }
      @flights_upsert_res =
        Flight.upsert(
          flight_atts,
          :returning => :id,
          :unique_by => %i[dep arr dep_at arr_at],
        )
      flight_id = @flights_upsert_res.first.fetch('id')
      parsed_flight.flight_id = flight_id
    end
  end

  # Can't use `updated_at`, because if nothing changes about the flight, then
  # updated_at is untouched.
  def expire_flights
    Flight
      .route(@search.route)
      .dep_date(@search.dep_on)
      .where.not(:id => @parsed_flights.filter_map(&:flight_id))
      .touch_all(:expired_at)
  end

  def upsert_fares
    @parsed_flights.each do |parsed_flight|
      parsed_fare = parsed_flight.fare
      next unless parsed_fare
      fare_atts = {
        :flight_id => parsed_flight.flight_id,
        :available => parsed_fare.available?,
      }
      if parsed_fare.available?
        price = parsed_fare.price
        fare_atts[price.type] =
          case price.type
          when :cash
            Integer(BigDecimal(price.value) * 100)
          when :points
            price.value
          else
            raise "Unknown price type: #{price.type}"
          end
      else
        # Assuming that if one isn't available, neither is the other.
        fare_atts[:points] = nil
        fare_atts[:cash]   = nil
      end
      res = Fare.upsert(
        fare_atts,
        :unique_by => :flight_id,
      )
    end
  end

end

app/models/search/request.rb
class Search::Request

  attr_reader :response
  attr_reader :dep
  attr_reader :arr
  attr_reader :dep_on
  attr_reader :currency

  def initialize(dep, arr, dep_on, currency)
    @dep      = dep
    @arr      = arr
    @dep_on   = dep_on
    @currency = currency
  end

  def call
    @response = conn.post do |req|
      req.body = body
    end
    raise @response.body unless @response.success?
    log_response
    @response
  end

private

  def log_response
    CachedSearch.save(self)
  end

  URL = 'https://www.southwest.com/api/air-booking/v1/air-booking/page/air/booking/shopping'

  SW_CURRENCIES = {
    :points => 'POINTS',
    :cash   => 'USD',
  }

  def conn
    @conn ||= conn = Faraday.new(
      :url => URL,
      :headers => headers_from_config,
    ) do |f|
      f.response :logger
    end
  end

  def headers_from_config
    eval File.read(Rails.root + 'config/search_headers.rb')
  end

  def body
    {
      :adultPassengersCount     => "1",
      :departureDate            => @dep_on.to_s,
      :departureTimeOfDay       => "ALL_DAY",
      :destinationAirportCode   => @arr,
      :fareType                 => SW_CURRENCIES.fetch(@currency.type),
      :int                      => "LFCBOOKAIR",
      :lapInfantPassengersCount => "0",
      :originationAirportCode   => @dep,
      :passengerType            => "ADULT",
      :promoCode                => "",
      :returnAirportCode        => "",
      :returnDate               => "",
      :returnTimeOfDay          => "ALL_DAY",
      :selectedFlight1          => "",
      :selectedFlight2          => "",
      :tripType                 => "oneway",
      :application              => "air-booking",
      :site                     => "southwest",
    }.to_json
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :set_route_from_param, :only => %i[new destroy]

  def new
    last_cached_search = CachedSearch.last
    pre_fill_route = @route || last_cached_search&.route
    pre_fill_date  = (params[:date] || last_cached_search&.dep_on || Date.today).to_date
    @search = Search.new(
      :dep      => pre_fill_route&.dep,
      :arr      => pre_fill_route&.arr,
      :dep_on   => pre_fill_date,
      :currency => last_cached_search&.currency || :points,
    )
  end

  def create
    search = Search.new(search_params)
    search.call
    redirect_to search_path(search.flights.first.route)
  end

  def show
    @route = Route.from_string(params[:id])
    @flights =
      Flight
        .available
        .route(@route)
        .includes(:fare)
    if @flights.any?
      @calcs = FlightsCalculations.new(@flights).tap(&:call)
      set_filter_settings
    else
      redirect_to new_search_path(
        :route => @route,
      )
    end

    @page_title = @route.to_s
  end

  def destroy
    Flight
      .route(@route)
      .dep_date(params[:date]) # NOTE This is wrong because of time zone.
      .destroy_all
    redirect_to search_path(@route)
  end

  def load_cached
    cached_search = CachedSearch.new(params[:path])
    cached_search.load
    redirect_to search_path(cached_search.route)
  end

private

  def search_params
    params
      .require(:search)
      .permit(
        :dep,
        :arr,
        :dep_on,
        :currency,
      )
  end

  def set_route_from_param
    @route = Route.from_string(params[:route]) if params[:route]
  end

  def set_filter_settings
    @filter_settings = {
      :dep => {
        :min => @calcs.dep_min,
        :max => @calcs.dep_max,
      },
      :arr => {
        :min => @calcs.arr_min,
        :max => @calcs.arr_max,
      },
      :duration => {
        :min => @calcs.duration_min,
        :max => @calcs.duration_max,
      },
      :stops => {
        :min => @calcs.stops_min,
        :max => @calcs.stops_max,
      },
      :kpoints => {
        :min => @calcs.kpoints_min,
        :max => @calcs.kpoints_max,
      },
      :layovers => @calcs.layovers,
    }
  end

  def cached_searches
    @cached_searches ||= CachedSearch.where(
      :route => params[:route],
      :date  => params[:date],
    )
  end
  helper_method :cached_searches

end

app/helpers/searches_helper.rb
module SearchesHelper

  def last_searched(route, date)
    CachedSearch.where(:route => route, :date => date).last&.created_on
  end

end

app/views/searches/_flight_tooltip.haml
%p.fs-6
  = flight.dep_at_in_time_zone.strftime('%R')
  \-
  = flight.arr_at_in_time_zone.strftime('%R')
  %br
  Dur: #{duration_in_words flight.duration}
  %br
  Stops: #{flight.layover_airports.presence || 0}
  - if flight.fare
    %br
    #{number_with_delimiter flight.fare.points} points
    - if flight.fare.cash
      %br
      #{number_to_currency(flight.fare.cash / 100.to_f, :precision => 0)}
      - if flight.fare.point_value
        %br
        Pt. val
        = flight.fare.point_value
%p.fs-6
  ID #{flight.id}
  %br
  c: #{flight.created_at}
  %br
  u: #{flight.updated_at}
  %br
  x: #{flight.expired_at}

app/views/searches/new.haml
%h1 Search

= form_with :model => @search do |f|
  .mb-2
    = f.label :dep
    = f.text_field :dep
  .mb-2
    = f.label :arr
    = f.text_field :arr
  .mb-2
    = f.label :dep_on
    = f.date_field :dep_on
  .mb-2
    = f.label :currency
    = f.collection_select :currency, Currency.all, :type, :type
  .mb-2
    = f.submit :search

- if cached_searches.any?
  %h3 Cached
  %ul.list-unstyled
    - cached_searches.each do |cached_search|
      %li= button_to cached_search.filename, load_cached_searches_path(:path => cached_search.path), :class => 'btn btn-outline-primary'

app/views/searches/new.html.haml
%h1 Search

= form_with :model => @search do |f|
  .mb-2
    = f.label :dep
    = f.text_field :dep
  .mb-2
    = f.label :arr
    = f.text_field :arr
  .mb-2
    = f.label :dep_on
    = f.date_field :dep_on
  .mb-2
    = f.label :currency
    = f.collection_select :currency, Currency.all, :type, :type
  .mb-2
    = f.submit :search

- if cached_searches.any?
  %h3 Cached
  %ul.list-unstyled
    - cached_searches.each do |cached_search|
      %li= button_to cached_search.filename, load_cached_searches_path(:path => cached_search.path), :class => 'btn btn-outline-primary'

app/views/searches/show.haml
%h1= @route

.flights{:data => {:controller => 'flights', :flights_flights_data_value => @flights.index_by(&:id).to_json(:include => [:fare], :methods => [:dep_at_hour, :arr_at_hour])}}

  - selectable_dates = @flights.map(&:dep_at).map(&:to_date).uniq.sort

  .mb-3.btn-group
    Departure Date
    - selectable_dates.each do |date|
      - input_id = "dep_date_#{date.to_s.underscore}"
      = check_box_tag input_id, :value => date.to_s, :checked => true, :class => 'btn-check', :data => {:flights_target => 'depDate', :action => 'flights#filterDates flights#filterFlights', :date => date.to_s}
      = label_tag input_id, date.to_s, :class => 'btn btn-outline-primary'
  .mb-3
    = label_tag :max_duration, 'Max duration in hours'
    = number_field_tag :max_duration, @filter_settings.fetch(:duration).fetch(:max), :data => {:flights_target => 'maxDuration', :action => 'flights#filterFlights'}, **@filter_settings.fetch(:duration)
    Avg: #{@calcs.duration_average}h
  .mb-3
    = label_tag :stops, 'Stops'
    = number_field_tag :stops, @filter_settings.fetch(:stops).fetch(:max), :data => {:flights_target => 'stops', :action => 'flights#filterFlights'}, **@filter_settings.fetch(:stops)
  .mb-3
    = label_tag :max_points, 'Max K-points'
    = number_field_tag :max_points, @filter_settings.fetch(:kpoints).fetch(:max), :data => {:flights_target => 'maxPoints', :action => 'flights#filterFlights'}, **@filter_settings.fetch(:kpoints)
    Avg: #{number_with_delimiter @calcs.points_average}
  - %i[dep arr].each do |dep_arr|
    .mb-3
      = dep_arr.to_s.titleize
      - %i[min max].each do |min_max|
        = label_tag "#{min_max}_#{dep_arr}_at", min_max
        = number_field_tag "#{min_max}_#{dep_arr}_at", @filter_settings.fetch(dep_arr).fetch(min_max), :data => {:flights_target => [min_max, dep_arr, 'at'].join('_').camelize(:lower), :action => 'flights#filterFlights'}, **@filter_settings.fetch(dep_arr)

  .results
    .row
      - selectable_dates.each do |date|
        .date-col.text-center{:data => {:flights_target => 'dateCol', :date => date}}
          %strong{:data => {:bs_toggle => 'tooltip'}, :title => "Updated #{last_searched(@route, date) || '?'}"}= date
          .small= date.strftime('%A')
          .btn-group
            = link_to 'Refresh', [:new, :search, :route => @route, :date => date], :class => 'btn btn-outline-primary'
            = button_to 'Delete', [:searches, :route => @route, :date => date], :method => :delete, :class => 'btn btn-outline-danger', :data => {:turbo_confirm => 'Sure?'}
          - @flights.group_by { |f| f.dep_at.to_date }.fetch(date).each do |flight|
            %div[flight]{:data => {:flights_target => 'flight', :id => flight.id}, :style => "left: #{flight.offset_duration_percent}%; width: #{flight.duration_percent}%"}
              .d-flex.justify-content-between
                .dep
                  -#.name= flight.dep
                  .at= flight.dep_at_in_time_zone.strftime('%R')
                .arr
                  -#.name= flight.arr
                  .at= flight.arr_at_in_time_zone.strftime('%R')
              - color = percent_progress_bar_color(flight.duration_weight_percent)
              .duration-line{:class => "text-#{color}", :data => {:bs_toggle => 'tooltip'}, :title => render('searches/flight_tooltip', :flight => flight)}= duration_in_words(flight.duration)
              - if flight.fare&.points
                .price{:class => "text-#{percent_progress_bar_color(flight.points_percent)}"}
                  %span.points= "#{flight.fare.kpoints}K"
                  - if flight.fare&.cash
                    \/
                    %span.cash= number_to_currency(flight.fare.cash / 100.to_f, :precision => 0)
                    - if flight.fare.point_value
                      \/
                      = flight.fare.point_value

app/views/searches/show.html.haml
%h1= @route

= link_to @route.reverse, :id => @route.reverse

.mt-3

.flights{:data => {:controller => 'flights', :flights_flights_data_value => @flights.index_by(&:id).to_json(:include => [:fare], :methods => [:dep_at_hour, :arr_at_hour])}}

  - selectable_dates = @flights.map(&:dep_at).map(&:to_date).uniq.sort

  .mb-3.btn-group
    Departure Date
    - selectable_dates.each do |date|
      - input_id = "dep_date_#{date.to_s.underscore}"
      = check_box_tag input_id, :value => date.to_s, :checked => true, :class => 'btn-check', :data => {:flights_target => 'depDate', :action => 'flights#filterDates flights#filterFlights', :date => date.to_s}
      = label_tag input_id, date.to_s, :class => 'btn btn-outline-primary'
  .mb-3
    = label_tag :max_duration, 'Max duration in hours'
    = number_field_tag :max_duration, @filter_settings.fetch(:duration).fetch(:max), :data => {:flights_target => 'maxDuration', :action => 'flights#filterFlights'}, **@filter_settings.fetch(:duration)
    Avg: #{@calcs.duration_average}h
  .mb-3
    = label_tag :stops, 'Stops'
    = number_field_tag :stops, @filter_settings.fetch(:stops).fetch(:max), :data => {:flights_target => 'stops', :action => 'flights#filterFlights'}, **@filter_settings.fetch(:stops)
  .mb-3
    = label_tag :max_points, 'Max K-points'
    = number_field_tag :max_points, @filter_settings.fetch(:kpoints).fetch(:max), :data => {:flights_target => 'maxPoints', :action => 'flights#filterFlights'}, **@filter_settings.fetch(:kpoints)
    Avg: #{number_with_delimiter @calcs.points_average}
  - %i[dep arr].each do |dep_arr|
    .mb-3
      = dep_arr.to_s.titleize
      - %i[min max].each do |min_max|
        = label_tag "#{min_max}_#{dep_arr}_at", min_max
        = number_field_tag "#{min_max}_#{dep_arr}_at", @filter_settings.fetch(dep_arr).fetch(min_max), :data => {:flights_target => [min_max, dep_arr, 'at'].join('_').camelize(:lower), :action => 'flights#filterFlights'}, **@filter_settings.fetch(dep_arr)
  .mb-3
    Layovers
    - @filter_settings.fetch(:layovers).each do |layover|
      .form-check
        - name = "layover_#{layover}"
        = check_box_tag name, layover, :checked => true, :class => 'form-check-input', :data => {:action => 'flights#filterFlights', :flights_target => 'layover'}
        = label_tag name, layover, :class => 'form-check-label'

  .results
    .row
      - selectable_dates.each do |date|
        .date-col.text-center{:data => {:flights_target => 'dateCol', :date => date}}
          %strong{:data => {:bs_toggle => 'tooltip'}, :title => "Updated #{last_searched(@route, date) || '?'}"}= date
          .small= date.strftime('%A')
          .btn-group
            = link_to 'Refresh', [:new, :search, :route => @route, :date => date], :class => 'btn btn-outline-primary'
            = button_to 'Delete', [:searches, :route => @route, :date => date], :method => :delete, :class => 'btn btn-outline-danger', :data => {:turbo_confirm => 'Sure?'}

          %br

          - cached_searches = CachedSearch.where(:route => @route, :date => date)
          - last_updated = cached_searches.last&.created_on&.to_date
          Updated #{last_updated}

          - @flights.group_by { |f| f.dep_at.to_date }.fetch(date).each do |flight|
            %div[flight]{:data => {:flights_target => 'flight', :id => flight.id}, :style => "left: #{flight.offset_duration_percent}%; width: #{flight.duration_percent}%"}
              .d-flex.justify-content-between
                .dep
                  -#.name= flight.dep
                  .at= flight.dep_at_in_time_zone.strftime('%R')
                .arr
                  -#.name= flight.arr
                  .at= flight.arr_at_in_time_zone.strftime('%R')
              - color = percent_progress_bar_color(flight.duration_weight_percent)
              .duration-line{:class => "text-#{color}", :data => {:bs_toggle => 'tooltip'}, :title => render('searches/flight_tooltip', :flight => flight)}= duration_in_words(flight.duration)
              - if flight.fare&.points
                .price{:class => "text-#{percent_progress_bar_color(flight.points_percent)}"}
                  %span.points= "#{flight.fare.kpoints}K"
                  - if flight.fare&.cash
                    \/
                    %span.cash= number_to_currency(flight.fare.cash / 100.to_f, :precision => 0)
                    - if flight.fare.point_value
                      \/
                      = flight.fare.point_value